### ISSUE TITLE
[Feature] Have BB automatically post `/announce-issue` in #github-updates

### ISSUE THREAD

**Issue by ghost** [GOF2BountyBot/GOF2BountyBot#923]
*(optional)* **Is your feature request related to a problem?**
If your idea solves a problem with the bot, tell us about it here E.g,: It's not fair when...

**Describe the solution you'd like**
What would your ideal solution look like? E.g: I'd like to be able to...

*(optional)* **Additional details**
Any extra details, context, screenshots, mockups, etc. etc.

*(optional)* **Your discord tag**
If you'd like to be credited for your idea in the bot's update announcements, you can give your discord tag here!

**Comment by Trimatix** [comment]
implemented with a webhook for now.

In the future, BB could subscribe to a webhook, so that issue updates can be enriched with labels and milestones, but that would be a bit of work to do. If an issue is submitted for this then I'm sure we can plan it in, but until then this is fine
