### ISSUE TITLE
my test issue

### ISSUE THREAD

**Issue by BountyBot-Official** [GOF2BountyBot/GOF2BountyBot#938]
<img src="https://cdn.discordapp.com/avatars/188618589102669826/6579bb36e96a9baf41b2d5ec263b231b.png?size=1024" align="left" width="96" height="96" hspace="10"></img> **Issue by [Trimatix#2244]**

_Originally opened via discord command_
_Issue type: Feature request_

----

**Is your feature request related to a problem?**
​

**Describe the solution you'd like**
I would like for this command to succeed and for my issue to appear in github!

**Attachments**
[dwayne.png](https://cdn.discordapp.com/attachments/729296521736224779/1069254918717845534/dwayne.png)
[coal_512.png](https://cdn.discordapp.com/attachments/729296521736224779/1069254918940151871/coal_512.png)

**Comment by Trimatix** [comment]
test passed, closing.
