### ISSUE TITLE
My test issue 2

### ISSUE THREAD

**Issue by BountyBot-Official** [GOF2BountyBot/GOF2BountyBot#939]
<img src="https://cdn.discordapp.com/avatars/188618589102669826/6579bb36e96a9baf41b2d5ec263b231b.png?size=1024" align="left" width="96" height="96" hspace="10"></img> **Issue by [Trimatix#2244]**

_Originally opened via discord command_
_Issue type: Feature request_

----

**Describe the solution you'd like**
Test issue sending to github

**Attachments**
[dwayne.png](https://cdn.discordapp.com/attachments/729296521736224779/1069258062608744509/dwayne.png)
[coal_512.png](https://cdn.discordapp.com/attachments/729296521736224779/1069258062877167716/coal_512.png)

**Comment by Trimatix** [comment]
test passed, closing
