### ISSUE TITLE
[Item Alias] a: t

### ISSUE THREAD

**Issue by BountyBot-Official** [GOF2BountyBot/GOF2BountyBot#941]
<img src="https://cdn.discordapp.com/avatars/188618589102669826/6579bb36e96a9baf41b2d5ec263b231b.png?size=1024" align="left" width="96" height="96" hspace="10"></img> **Issue by [Trimatix#2244]**

_Originally opened via discord command_
_Issue type: New item alias_

----

**The item**
a

**New alias**
t

**Comment by Trimatix** [comment]
test passed, closing
